#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#server:
#  port: 8761
#
#spring:
#  application:
#    name: eureka
#
#server:
#  port: 8761
#
#eureka:
#  instance:
#    prefer-ip-address: false
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#
#server:
#  port: ${PORT:8761}
#
#eureka:
##  instance:
###    hostname: ${EUREKA_HOSTNAME:localhost}
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: https://copic-service-registry.herokuapp.com/
##      defaultZone: http://user:password@${eureka.instance.hostname}:${server.port}/eureka/}
#

server:
  port: ${PORT:5000}

eureka:
  instance:
    hostname: copic-service-registry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

